# Generated by Django 5.1.7 on 2025-04-03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Asegúrate de tener esta dependencia si el modelo Sensor ya fue migrado antes
        # ('tu_app', '0001_initial_sensor'),  # Reemplaza 'tu_app' por el nombre real de tu app
    ]

    operations = [
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id_medicion', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fecha_creacion', models.DateTimeField()),
                ('id_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, db_column='id_sensor', to='tu_app.sensor')),
            ],
            options={
                'managed': False,
                'db_table': 'medicion',
            },
        ),
    ]

