# Generated by Django 5.2 on 2025-04-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('id_dispositivo', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'sensor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoSensor',
            fields=[
                ('id_tipo_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_sensor', models.CharField(max_length=50, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('unidad_medida', models.CharField(max_length=100)),
                ('valor_recomendado', models.CharField(max_length=50)),
                ('valor_max', models.CharField(max_length=50)),
                ('voltaje', models.CharField(max_length=5)),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'tipo_sensor',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='medicion',
            options={'managed': False},
        ),
    ]
